/**
 * CLI definition.
 *
 * Generated by ph-clint. Regions bracketed by @clint:begin/@clint:end
 * markers are rewritten by ph-clint when the project spec changes.
 * Everything outside the markers is user-editable and preserved.
 */
// @clint:begin imports
import { defineCli, buildDefaultReactor } from '@powerhousedao/ph-clint';
import { z } from 'zod';
import path from 'node:path';
import { CLI_NAME, CLI_VERSION, CLI_ROOT } from './config.js';
import { configSchema, secretsSchema } from './framework.js';
import { documentModels } from 'vetra-app';
import { documentModels as extModels } from '@powerhousedao/clint-common';
import { createAgent } from './agents/agent.js';
import { chatSessionWatchTrigger } from '@powerhousedao/clint-common/chat';
import { observability } from '@powerhousedao/ph-clint-observability';
import { specCommands } from './commands/spec/index.js';
import { reactorProjectCommands } from './commands/reactor-project/index.js';
// @clint:end imports

export const cli = defineCli({
  name: CLI_NAME,
  version: CLI_VERSION,
  // @clint:begin root
  root: CLI_ROOT,
  // @clint:end root
  description: `${CLI_NAME} v${CLI_VERSION}`,
  configSchema,
  secretsSchema,

  // @clint:begin commands
  commands: [
    ...specCommands,
    ...reactorProjectCommands,
  ],
  // @clint:end commands

  // @clint:begin services
  services: [],
  // @clint:end services

  // @clint:begin triggers
  triggers: [chatSessionWatchTrigger],
  // @clint:end triggers

  // @clint:begin prompts
  prompts: {
    artifacts: [path.join(CLI_ROOT, 'gen', 'skills'), path.join(CLI_ROOT, 'dist', 'gen', 'skills')],
    agents: {
      'vetra-agent': {
        name: 'vetra-agent',
        sections: ['base.md'],
        skills: ['reactor-project-management'],
      },
      'agent-document-model': {
        name: 'agent-document-model',
        sections: ['base.md'],
        skills: [],
      },
      'agent-editor': {
        name: 'agent-editor',
        sections: ['base.md'],
        skills: [],
      },
    },
    skills: {
      'reactor-project-management': {
        description: 'Initialize, build, and publish Reactor Package projects',
        inputSchema: z.object({
          mode: z
            .enum(['expert', 'discovery', 'one-shot'])
            .default('expert')
            .describe(
              'Expert: align technical design decisions between fellow experts. Discovery: explain the process and guide non-expert users to decisions. One-shot: make all design decisions autonomously and execute without asking',
            ),
        }),
        instructionTemplate:
          'Use your {{skillId}} skill in {{mode}} mode for: {{prompt}}',
      },
    },
  },
  // @clint:end prompts

  // @clint:begin events
  events: {},
  // @clint:end events

  // @clint:begin proxy
  // @clint:end proxy

  // @clint:begin lifecycle
  lifecycle: [observability()],
  // @clint:end lifecycle

  // @clint:begin interactive
  interactive: {
    welcome: ({ workdir }) =>
      [
        `${CLI_NAME} v${CLI_VERSION}`,
        `Workdir: ${workdir}`,
        '',
        'Type a message to talk to the agent, or / for commands.',
      ].join('\n'),
  },
  // @clint:end interactive
});

// @clint:begin reactor
cli.configureReactor({
  create: (ctx) =>
    buildDefaultReactor(ctx, {
      documentModels: [...documentModels, ...extModels],
      drive: { name: 'vetra-cli' },
      subscriptions: {},
    }),
  switchboard: { enabled: true },
  connect: { enabled: true },
});
// @clint:end reactor

// @clint:begin mastra
cli.configureAgent(createAgent);
// @clint:end mastra
