/**
 * CLI definition.
 *
 * Generated by ph-clint. Regions bracketed by @clint:begin/@clint:end
 * markers are rewritten by ph-clint when the project spec changes.
 * Everything outside the markers is user-editable and preserved.
 */
// @clint:begin imports
import { defineCli, buildDefaultReactor, deterministicId } from '@powerhousedao/ph-clint';
import { z } from 'zod';
import path from 'node:path';
import { CLI_NAME, CLI_VERSION, CLI_ROOT } from './config.js';
import { configSchema, secretsSchema } from './framework.js';
import { documentModels } from 'vetra-app';
import { documentModels as vetraModels } from '@powerhousedao/vetra';
import { documentModels as extModels } from '@powerhousedao/clint-common';
import { createAgent } from './agents/agent.js';
import { chatSessionWatchTrigger } from '@powerhousedao/clint-common/chat';
import { observability } from '@powerhousedao/ph-clint-observability';
import { agentRun } from './commands/agent-run.js';
import { specCommands } from './commands/spec/index.js';
import { specPreviewCommands } from './commands/spec-preview/index.js';
import { reactorProjectCommands } from './commands/reactor-project/index.js';
import { reactorProject } from './services/reactor-project.js';
import { localRegistry } from './services/local-registry.js';
import { LOCAL_REGISTRY_ENABLED, LOCAL_REGISTRY_URL } from './constants.js';
import { specSyncTrigger } from './triggers/spec-sync.js';
import { specFsSyncTrigger } from './triggers/spec-fs-sync.js';
import { publishReloadTrigger } from './triggers/publish-reload.js';
import { previewServerTrigger } from './triggers/preview-server.js';
import { connectDriveUrlOnSwitchboardReady } from './lifecycle/connect-drive-url.js';
import { DEFAULT_PREVIEW_SERVER_PORT } from './preview-server/index.js';
import { genGuard } from './lifecycle/gen-guard.js';
import { tsCheck } from './lifecycle/ts-check.js';
import { studioUrlTrigger } from './triggers/studio-url.js';
import { DocumentModelModule } from '@powerhousedao/shared/document-model';
// @clint:end imports
import { createClaudeAuthCommands } from '@powerhousedao/ph-clint-claude-subscription';
import { createAttachmentCommands } from '@powerhousedao/ph-clint/powerhouse';

export const cli = defineCli({
  name: CLI_NAME,
  version: CLI_VERSION,
  // @clint:begin root
  root: CLI_ROOT,
  // @clint:end root
  description: `${CLI_NAME} v${CLI_VERSION}`,
  configSchema,
  secretsSchema,

  // @clint:begin commands
  commands: [
    ...specCommands,
    ...specPreviewCommands,
    ...reactorProjectCommands,
    ...createAttachmentCommands(),
    agentRun,
    // claude-login / claude-logout / claude-status — Claude.ai subscription
    // auth (user scope: one login shared across workdirs).
    ...createClaudeAuthCommands({ cliName: CLI_NAME }),
  ],
  // @clint:end commands

  // @clint:begin services
  services: [reactorProject, ...(LOCAL_REGISTRY_ENABLED ? [localRegistry] : [])],
  // @clint:end services

  // @clint:begin triggers
  triggers: [
    chatSessionWatchTrigger,
    specSyncTrigger,
    specFsSyncTrigger,
    previewServerTrigger,
    studioUrlTrigger,
    ...(LOCAL_REGISTRY_ENABLED ? [publishReloadTrigger] : []),
  ],
  // @clint:end triggers

  // @clint:begin prompts
  prompts: {
    artifacts: [path.join(CLI_ROOT, 'gen', 'skills'), path.join(CLI_ROOT, 'dist', 'gen', 'skills')],
    agents: {
      'vetra-agent': {
        name: 'vetra-agent',
        sections: ['base.md', 'tools.md', 'workflow.md'],
        skills: ['reactor-project-management', 'document-modeling', 'document-editor-creation', 'drive-app-creation'],
      },
      'agent-document-model': {
        name: 'agent-document-model',
        sections: ['base.md', 'tools.md'],
        skills: ['document-modeling'],
      },
      'agent-editor': {
        name: 'agent-editor',
        sections: ['base.md', 'tools.md'],
        skills: ['document-editor-creation'],
      },
      'agent-app': {
        name: 'agent-app',
        sections: ['base.md', 'tools.md'],
        skills: ['drive-app-creation'],
      },
    },
    skills: {
      'reactor-project-management': {
        description: 'Initialize, build, and publish Reactor Package projects',
        inputSchema: z.object({
          mode: z
            .enum(['expert', 'discovery', 'one-shot'])
            .default('expert')
            .describe(
              'Expert: align technical design decisions between fellow experts. Discovery: explain the process and guide non-expert users to decisions. One-shot: make all design decisions autonomously and execute without asking',
            ),
        }),
        instructionTemplate:
          'Use your {{skillId}} skill in {{mode}} mode for: {{prompt}}',
      },
      'document-modeling': {
        description: 'Design Powerhouse document models with state schemas, operations, and reducers',
        inputSchema: z.object({
          mode: z
            .enum(['expert', 'discovery', 'one-shot'])
            .default('expert')
            .describe(
              'Expert: align technical design decisions between fellow experts. Discovery: explain the process and guide non-expert users to decisions. One-shot: make all design decisions autonomously and execute without asking',
            ),
        }),
        instructionTemplate:
          'Use your {{skillId}} skill in {{mode}} mode for: {{prompt}}',
      },
      'document-editor-creation': {
        description: 'Build React editor components for Powerhouse document types',
        inputSchema: z.object({
          mode: z
            .enum(['expert', 'discovery', 'one-shot'])
            .default('expert')
            .describe(
              'Expert: align technical design decisions between fellow experts. Discovery: explain the process and guide non-expert users to decisions. One-shot: make all design decisions autonomously and execute without asking',
            ),
        }),
        instructionTemplate:
          'Use your {{skillId}} skill in {{mode}} mode for: {{prompt}}',
      },
      'drive-app-creation': {
        description: 'Build drive-level app components (dashboards, kanban boards, custom drive views) for Powerhouse drives',
        inputSchema: z.object({
          mode: z
            .enum(['expert', 'discovery', 'one-shot'])
            .default('expert')
            .describe(
              'Expert: align technical design decisions between fellow experts. Discovery: explain the process and guide non-expert users to decisions. One-shot: make all design decisions autonomously and execute without asking',
            ),
        }),
        instructionTemplate:
          'Use your {{skillId}} skill in {{mode}} mode for: {{prompt}}',
      },
    },
  },
  // @clint:end prompts

  // @clint:begin events
  events: {
    'service:pattern-matched': (event, log) => {
      log.info(`  ✓ ${event.patternName} matched (${event.remaining} remaining)`);
    },
    'service:ready': (event, log) => {
      const ep = event.endpoints ?? {};
      log.info(
        `✓ ${event.name} is ready` +
          (ep['vetra-studio'] ? ` — Vetra Studio at ${ep['vetra-studio']}` : ''),
      );
    },
    'service:failed': (event, log) => {
      log.error(`✗ ${event.name} failed: ${event.error}`);
      if (event.id === 'reactor-project' && /exited before becoming ready/.test(event.error ?? '')) {
        log.info(
          '  Hint: Is the working directory a Reactor package project? Try: reactor-project-start --workdir <project-name>',
        );
      }
      if (/max instances/.test(event.error ?? '')) {
        log.info(
          `  Hint: ${event.name} is already running. Stop it first with ${event.id}-stop, or use ${event.id}-restart.`,
        );
      }
    },
    'service:restarting': (event, log) => {
      log.warn(`↻ ${event.name} restarting (attempt ${event.attempt}/${event.maxRetries})`);
    },
    'service:stopped': (event, log) => {
      log.info(`■ ${event.name} stopped`);
    },
    'package:reload-failed': (event: unknown, log) => {
      const { packageName, version, target, error } = event as {
        packageName: string;
        version: string;
        target: 'switchboard' | 'connect';
        error: string;
      };
      log.error(
        `✗ Failed to reload ${packageName}@${version} on ${target}: ${error}`,
      );
    },
  },
  // @clint:end events

  // @clint:begin proxy
  proxyEnabled: true,
  // @clint:end proxy
  proxyRoutes: [
    // Browser-facing preview-server route — vetra-studio (served at the proxy
    // root) reaches /resolve, /start, and the SSE /events stream same-origin.
    {
      prefix: '/preview',
      upstream: `http://127.0.0.1:${DEFAULT_PREVIEW_SERVER_PORT}`,
    },
  ],

  // @clint:begin lifecycle
  lifecycle: [
    observability(),
    genGuard(),
    tsCheck(),
    connectDriveUrlOnSwitchboardReady({
      vetraAppDir: path.resolve(CLI_ROOT, '..', 'vetra-app'),
    }),
  ],
  // @clint:end lifecycle

  configDefaults: {
    sentryDsn: "https://a0195e4737951326d23f18b05df6e947@sentry.monitoring.vetra.io/4",
    // Pin the proxy port so browser-facing URLs (stamped drive URL, iframe
    // paths) survive daemon restarts; 0 would auto-assign per session.
    proxyPort: 8090,
  },

  // @clint:begin interactive
  interactive: {
    welcome: ({ workdir }) =>
      [
        `${CLI_NAME} v${CLI_VERSION}`,
        `Workdir: ${workdir}`,
        '',
        'Type a message to talk to the agent, or / for commands.',
      ].join('\n'),
  },
  // @clint:end interactive
});

// @clint:begin reactor
cli.configureReactor({
  create: (ctx) =>
    buildDefaultReactor(ctx, {
      documentModels: [...documentModels, ...vetraModels, ...extModels] as DocumentModelModule<any>[],
      drive: {
        name: 'vetra-cli',
        // Salt with the absolute workdir so each workdir is its own drive
        // (stable across restarts, distinct across workdirs).
        id: deterministicId(CLI_NAME, path.resolve(ctx.workdir)),
        preferredEditor: 'vetra-studio',
      },
      subscriptions: {},
    }),
  switchboard: {
    enabled: true,
    // Wire the local-registry's URL into the embedded switchboard so the
    // `Packages` GraphQL subgraph picks it up — required for the
    // publish-reload trigger's install/uninstall mutations.
    ...(LOCAL_REGISTRY_ENABLED ? { registryUrl: LOCAL_REGISTRY_URL } : {}),
  },
  connect: {
    enabled: true,
    // Forwarded to Connect's vite config as PH_CONNECT_PACKAGES_REGISTRY so
    // the browser fetches Powerhouse package bundles from the local registry.
    ...(LOCAL_REGISTRY_ENABLED ? { registryUrl: LOCAL_REGISTRY_URL } : {}),
  },
});
// @clint:end reactor

// @clint:begin mastra
cli.configureAgent(createAgent);
// @clint:end mastra
