/**
 * Blocks the agent's workspace write/edit tools from touching document-model
 * codegen output inside a reactor project.
 *
 * Files under `<project>/document-models/<model>/.../gen/` are regenerated by
 * `spec-generate` and clobbered on every run. Past agent sessions have hand-
 * patched these files when codegen produced errors, which papers over the
 * underlying spec problem (and silently breaks again at the next regen).
 * The rule lives in the skill prompts; this hook makes it a deterministic
 * tool error so the agent self-corrects on the first try.
 *
 * Scope is intentionally narrow — only `document-models/`. Editors,
 * processors, and subgraphs have editable source siblings the agent needs
 * to write (most notably `editors/<e>/editor.tsx`), and broadening the
 * regex risks false positives there.
 *
 * Hook point: ph-clint already routes every Mastra tool through
 * `ctx.wraps.tool(name, tool)` (see
 * `ph-clint/packages/ph-clint/src/integrations/mastra/index.ts`). We
 * contribute a `tool` wrap that recognises the two writing workspace tools
 * by name, inspects `args.path`, and throws before the inner execute runs.
 */
import type { LifecycleHook } from "@powerhousedao/ph-clint";

const WRITE_TOOLS = new Set([
  "mastra_workspace_write_file",
  "mastra_workspace_edit_file",
]);

/* A document-model codegen path looks like
 * `.../document-models/<model>/v1/gen/...` (versioned) or
 * `.../document-models/<model>/gen/...` (no version dir). Match the model
 * dir followed by any number of intermediate segments and then `gen`. */
const GEN_PATH_RE =
  /(?:^|\/)document-models\/[^/]+\/(?:[^/]+\/)*gen(?:\/|$)/;

export function isCodegenPath(p: string): boolean {
  return GEN_PATH_RE.test(p.replace(/\\/g, "/"));
}

function extractPath(args: unknown): string | undefined {
  if (typeof args !== "object" || args === null) return undefined;
  const path = (args as { path?: unknown }).path;
  return typeof path === "string" && path.length > 0 ? path : undefined;
}

export function genGuard(): LifecycleHook {
  return {
    name: "gen-guard",
    onInit() {
      return {
        contribute: {
          tool(name, tool) {
            if (!WRITE_TOOLS.has(name)) return tool;
            const innerExecute = tool.execute.bind(tool);
            return {
              ...tool,
              execute: (args: unknown) => {
                const path = extractPath(args);
                if (path && isCodegenPath(path)) {
                  throw new Error(
                    `${name}: refusing to write under a document-model codegen ` +
                      `directory (\`${path}\`). Files under ` +
                      "`<reactor-project>/document-models/<model>/.../gen/` are " +
                      "regenerated by `spec-generate` and any hand-edit is " +
                      "clobbered on the next run. Fix the spec (`spec-update`) " +
                      "and re-run `spec-generate` instead. Reducer source lives " +
                      "at `<v1>/src/reducers/<module>.ts` — that's NOT under " +
                      "`gen/` and is the right target for `mastra_workspace_edit_file`.",
                  );
                }
                return innerExecute(args);
              },
            };
          },
        },
      };
    },
  };
}
