#!/usr/bin/env tsx
/**
 * Build script — compiles Handlebars templates in `prompts/` into static
 * SKILL.md files and agent instruction strings under `gen/`, then copies
 * and finalizes `powerhouse.manifest.json` into `dist/`.
 */
import fs from 'node:fs';
import path from 'node:path';
import { build as tsdownBuild } from 'tsdown';
import { buildSkills } from '@powerhousedao/ph-clint-dev';
import { buildManifest } from '@powerhousedao/ph-clint-dev/manifest';
import { cli } from '../src/cli.js';

const PROJECT_ROOT = path.resolve(import.meta.dirname, '..');

/**
 * Regenerate `src/ph-version.gen.ts` from the workspace catalog so the
 * default Powerhouse version for new reactor projects tracks the version
 * vetra's runtime is built against. The catalog pins every
 * `@powerhousedao/*` package to the same version; we read `ph-cli` as the
 * marker since `ph init` installs that stack.
 */
function writePhVersion(): void {
  const workspaceFile = path.resolve(PROJECT_ROOT, '..', 'pnpm-workspace.yaml');
  const genFile = path.join(PROJECT_ROOT, 'src', 'ph-version.gen.ts');
  if (!fs.existsSync(workspaceFile)) {
    console.warn(`build-assets: ${workspaceFile} not found; keeping existing ph-version.gen.ts`);
    return;
  }
  const catalog = fs.readFileSync(workspaceFile, 'utf-8');
  const match = catalog.match(/^\s*['"]@powerhousedao\/ph-cli['"]:\s*['"]([^'"]+)['"]/m);
  if (!match?.[1]) {
    console.warn('build-assets: @powerhousedao/ph-cli not found in catalog; keeping existing ph-version.gen.ts');
    return;
  }
  const contents = `// Generated by scripts/build-assets.ts from the pnpm-workspace.yaml catalog.
// Do not edit by hand — run \`pnpm build:assets\` to regenerate.
export const DEFAULT_PH_VERSION = '${match[1]}';
`;
  fs.writeFileSync(genFile, contents);
}

writePhVersion();

// @clint:begin templateVars
function loadTemplateVars(): Record<string, string> {
  return {
    agentName: '{{AGENT_NAME}}',
  };
}
// @clint:end templateVars

buildSkills({
  include: [path.join(PROJECT_ROOT, 'prompts')],
  context: loadTemplateVars(),
  output: [
    path.join(PROJECT_ROOT, 'gen'),
    path.join(PROJECT_ROOT, 'dist', 'gen'),
  ],
  cli,
});

await buildManifest({
  srcDir: PROJECT_ROOT,
  outDir: path.join(PROJECT_ROOT, 'dist'),
  cli,
});

// The bundled CLI spawns `node <dist>/connect-server.js` for the studio static
// server; sirv/totalist aren't in the prod install, so bundle it self-contained.
async function bundleConnectServer(): Promise<void> {
  const rel = path.join('dist', 'integrations', 'powerhouse', 'connect-server.js');
  const candidates = [
    path.join(PROJECT_ROOT, 'node_modules', '@powerhousedao', 'ph-clint', rel),
    path.join(PROJECT_ROOT, '..', 'node_modules', '@powerhousedao', 'ph-clint', rel),
  ];
  const src = candidates.find((p) => fs.existsSync(p));
  if (!src) {
    console.warn('build-assets: ph-clint connect-server.js not found; studio static server will be missing');
    return;
  }
  // node builtins stay external; sirv/totalist + the lazy import('totalist') inline.
  await tsdownBuild({
    config: false,
    entry: { 'connect-server': src },
    outDir: path.join(PROJECT_ROOT, 'dist'),
    format: ['esm'],
    platform: 'node',
    target: 'node22',
    dts: false,
    clean: false,
    sourcemap: false,
    silent: true,
    codeSplitting: false,
    deps: { alwaysBundle: ['sirv', 'totalist'] },
    outputOptions: { entryFileNames: '[name].js' },
  });
  console.log('build-assets: bundled connect-server.js -> dist/');
}
await bundleConnectServer();

// Ship the prebuilt Connect SPA in vetra's own dist (served from
// CLI_ROOT/dist/connect) so vetra-app can be a devDep. Skips if already current.
function copyConnectBundle(): void {
  const src = path.join(PROJECT_ROOT, '..', 'vetra-app', 'dist', 'connect');
  const dest = path.join(PROJECT_ROOT, 'dist', 'connect');
  if (!fs.existsSync(path.join(src, 'index.html'))) {
    console.warn('build-assets: vetra-app/dist/connect not found; run `pnpm --filter vetra-app build:connect` first');
    return;
  }
  const destIndex = path.join(dest, 'index.html');
  if (fs.existsSync(destIndex) &&
      fs.statSync(destIndex).mtimeMs >= fs.statSync(path.join(src, 'index.html')).mtimeMs) {
    console.log('build-assets: dist/connect already current; skipping copy');
    return;
  }
  fs.rmSync(dest, { recursive: true, force: true });
  fs.cpSync(src, dest, { recursive: true });
  console.log('build-assets: copied vetra-app/dist/connect -> dist/connect');
}
copyConnectBundle();
