#!/usr/bin/env tsx
/**
 * Build script — compiles Handlebars templates in `prompts/` into static
 * SKILL.md files and agent instruction strings under `gen/`, then copies
 * and finalizes `powerhouse.manifest.json` into `dist/`.
 */
import fs from 'node:fs';
import path from 'node:path';
import { buildSkills } from '@powerhousedao/ph-clint-dev';
import { buildManifest } from '@powerhousedao/ph-clint-dev/manifest';
import { cli } from '../src/cli.js';

const PROJECT_ROOT = path.resolve(import.meta.dirname, '..');

/**
 * Regenerate `src/ph-version.gen.ts` from the workspace catalog so the
 * default Powerhouse version for new reactor projects tracks the version
 * vetra-cli's runtime is built against. The catalog pins every
 * `@powerhousedao/*` package to the same version; we read `ph-cli` as the
 * marker since `ph init` installs that stack.
 */
function writePhVersion(): void {
  const workspaceFile = path.resolve(PROJECT_ROOT, '..', 'pnpm-workspace.yaml');
  const genFile = path.join(PROJECT_ROOT, 'src', 'ph-version.gen.ts');
  if (!fs.existsSync(workspaceFile)) {
    console.warn(`build-assets: ${workspaceFile} not found; keeping existing ph-version.gen.ts`);
    return;
  }
  const catalog = fs.readFileSync(workspaceFile, 'utf-8');
  const match = catalog.match(/^\s*['"]@powerhousedao\/ph-cli['"]:\s*['"]([^'"]+)['"]/m);
  if (!match?.[1]) {
    console.warn('build-assets: @powerhousedao/ph-cli not found in catalog; keeping existing ph-version.gen.ts');
    return;
  }
  const contents = `// Generated by scripts/build-assets.ts from the pnpm-workspace.yaml catalog.
// Do not edit by hand — run \`pnpm build:assets\` to regenerate.
export const DEFAULT_PH_VERSION = '${match[1]}';
`;
  fs.writeFileSync(genFile, contents);
}

writePhVersion();

// @clint:begin templateVars
function loadTemplateVars(): Record<string, string> {
  return {
    agentName: '{{AGENT_NAME}}',
  };
}
// @clint:end templateVars

buildSkills({
  include: [path.join(PROJECT_ROOT, 'prompts')],
  context: loadTemplateVars(),
  output: [
    path.join(PROJECT_ROOT, 'gen'),
    path.join(PROJECT_ROOT, 'dist', 'gen'),
  ],
  cli,
});

await buildManifest({
  srcDir: PROJECT_ROOT,
  outDir: path.join(PROJECT_ROOT, 'dist'),
  cli,
});
